### ISSUE TITLE
Desktop target

### ISSUE THREAD

**Issue by Savrov** [kalinjul/kotlin-multiplatform-oidc#11]
Hello, firstly, thank you for providing such a valuable library; it saved me a considerable amount of time today! 👏🏻

Upon reviewing the source code, I noticed your exploration into Desktop support. I'm curious when we can anticipate its release. Is there any way I can assist you with the development?

**Comment by kalinjul** [comment]
Hi, thanks for you kind words.
I do not have a plan for complete desktop support yet, mainly because i don't have the use case.

However, some modules already work on desktop (oidc-core and oidc-crypto).
The missing pieces are the tokenstore, which could simply be implemented as unencrypted file store, and the Authorization Flow itself (in oidc-appsupport).

On iOS/Android we're using platform-specific methods for opening a browser and catching the redirect. Those are not available for jvm/desktop.

I think there are two options here: Open a browser window, start an embedded webserver that listens for the redirect. This would only allow redirect urls with i.e. _localhost:8080/_.
Second option could be to embed a Web View and catch redirects from there (I have no idea if this is really possible).

Would the first option apply to your use case? Do you have other ideas?

**Comment by Savrov** [comment]
> I think there are two options here: Open a browser window, start an embedded webserver that listens for the redirect. This would only allow redirect urls with i.e. localhost:8080/.

Actually I already had some my own implementation (byt much "easier" in meaning of functionality), so the 1.st option was just fine for me (:

**Comment by kalinjul** [comment]
> > I think there are two options here: Open a browser window, start an embedded webserver that listens for the redirect. This would only allow redirect urls with i.e. localhost:8080/.
> 
> Actually I already had some my own implementation (byt much "easier" in meaning of functionality), so the 1.st option was just fine for me (:

You can check out version 0.8.0 where i added some rudimentary desktop support
