### ISSUE TITLE
JVM AppSupport displays 406 after successfull authentication

### ISSUE THREAD

**Issue by ghost** [kalinjul/kotlin-multiplatform-oidc#65]
When the [JVM OAuth Flow](https://github.com/kalinjul/kotlin-multiplatform-oidc/blob/main/oidc-appsupport/src/jvmMain/kotlin/org/publicvalue/multiplatform/oidc/appsupport/PlatformOidcCodeAuthFlow.jvm.kt) is triggered on a Desktop application, it ends a successful authentication attempt with a 406 error in the browser that confuses users:

<img width="704" alt="Bildschirmfoto 2024-08-12 um 15 34 36" src="https://github.com/user-attachments/assets/92fec5ad-5b83-45db-ba7d-2b98f7bdce87">

Since the webserver is immediately shut down afterwards, a reload obviously does not help.

A better approach would be to display some kind of informational message to the user that he can close the browser window and return to his application or alternatively use one of the multiplatform webkit / webview implementations (like https://github.com/KevinnZou/compose-webview-multiplatform)

**Comment by realdadfish** [comment]
Eventually it would be cool if the flow could redirect the browser to a custom, configurable redirect URI anyways, something like `myapp://my.package/auth-finished` so that when the app installs a protocol handler in the system the browser prompts the user to switch back / open the application again ([described more in detail here](https://help.autodesk.com/view/SGDEV/ENU/?guid=SGD_ami_custom_browser_protocols_html#registering-a-protocol-on-windows)).

**Comment by uliluckas** [comment]
It would probably be enough, if the embedded web server could serve a configurable response to the redirect request.
